#!/usr/bin/env sh
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$SCRIPT_DIR/trilobite-runtime.sh"
if [ -z "${TRILOBITE_PYTHON:-}" ]; then
  echo "[trilobite] ERROR: no bundled or system Python runtime was found." >&2
  exit 3
fi

export LOCAL_LLM_NUM_THREAD=${LOCAL_LLM_NUM_THREAD:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}
export LOCAL_LLM_NUM_GPU=${LOCAL_LLM_NUM_GPU:-999}
export LOCAL_LLM_NUM_BATCH=${LOCAL_LLM_NUM_BATCH:-512}
export OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
export TRILOBITE_ENDLESS_TOTAL=${TRILOBITE_ENDLESS_TOTAL:-30}
export TRILOBITE_ENDLESS_LANGUAGES=${TRILOBITE_ENDLESS_LANGUAGES:-python,javascript,powershell,cpp,csharp}
export TRILOBITE_ENDLESS_TIER=${TRILOBITE_ENDLESS_TIER:-fast}
export TRILOBITE_ENDLESS_WORKERS=${TRILOBITE_ENDLESS_WORKERS:-4}
export TRILOBITE_ENDLESS_TIMEOUT=${TRILOBITE_ENDLESS_TIMEOUT:-10}
export TRILOBITE_ENDLESS_REPAIRS=${TRILOBITE_ENDLESS_REPAIRS:-2}
export TRILOBITE_ENDLESS_SLEEP=${TRILOBITE_ENDLESS_SLEEP:-2}
export TRILOBITE_ENDLESS_STOP_AFTER_NO_PROGRESS=${TRILOBITE_ENDLESS_STOP_AFTER_NO_PROGRESS:-1}

exec "$TRILOBITE_PYTHON" "$SCRIPT_DIR/endless_train.py" "$@"
